Conflict with sqlalchemy_enum34
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 199fb97490c, empty message
Traceback (most recent call last):
  File "manage.py", line 32, in <module>
    manager.run()
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/flask_migrate/__init__.py", line 195, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "migrations/env.py", line 73, in <module>
    run_migrations_online()
  File "migrations/env.py", line 66, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/runtime/environment.py", line 788, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/opt/pyenv/versions/3.4.2-server/lib/python3.4/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/Volumes/Unsigned/server/migrations/versions/199fb97490c_.py", line 24, in upgrade
    sa.Column('type', migration_types.Enum('rejected', 'accepted', 'notresponsed'), nullable=False),
TypeError: <flask_script.commands.Command object at 0x108f84828>: __call__() takes from 2 to 3 positional arguments but 4 were given